In [5]:
from google.colab import files
uploaded = files.upload()

Saving bbc_text_cls.csv to bbc_text_cls.csv

In [12]:
import pandas as pd
df=pd.read_csv('bbc_text_cls.csv')
df.head()

                                                text    labels
0  Ad sales boost Time Warner profit\n\nQuarterly...  business
1  Dollar gains on Greenspan speech\n\nThe dollar...  business
2  Yukos unit buyer faces loan claim\n\nThe owner...  business
3  High fuel prices hit BA's profits\n\nBritish A...  business
4  Pernod takeover talk lifts Domecq\n\nShares in...  business

In [13]:
df.shape

(2225, 2)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2225 entries, 0 to 2224
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    2225 non-null   object
 1   labels  2225 non-null   object
dtypes: object(2)
memory usage: 34.9+ KB

In [15]:
df['labels'].value_counts()

labels
sport            511
business         510
politics         417
tech             401
entertainment    386
Name: count, dtype: int64

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X = df['text']
y = df['labels']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [20]:
print(X_train.shape)
print(X_test.shape)

(1780,)
(445,)

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [22]:
tf=TfidfVectorizer()

In [23]:
X_train_tfidf=tf.fit_transform(X_train)
X_test_tfidf=tf.transform(X_test)

In [24]:
from sklearn.naive_bayes import MultinomialNB

In [25]:
model=MultinomialNB()
model.fit(X_train_tfidf,y_train)

MultinomialNB()

In [26]:
y_pred=model.predict(X_test_tfidf)

In [27]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.952808988764045

In [28]:
sample = ["Apple announces new AI powered MacBook"]
sample_tfidf = tf.transform(sample)
print(model.predict(sample_tfidf))

['tech']

In [30]:
sample=['babar azam lose his wicket again as he did everytime']
sample_tfidf=tf.transform(sample)
print(model.predict(sample_tfidf))

['sport']

In [31]:
sample=['Mehran university has got fuckin alot of problems']
sample_tfidf=tf.transform(sample)
print(model.predict(sample_tfidf))

['politics']

In [29]:
df.columns

Index(['text', 'labels'], dtype='object')